### ISSUE TITLE
Commit message does not matched.

### ISSUE THREAD

**Issue by Thiritin** [ChanTsune/release-with-commit#160]
Hey on my Setup the workflow succeeds but no release is created.

Release v0.0.3-alpha Change to main branch
Commit message does not matched.

Commit Message: `Release v0.0.3-alpha Change to main branch`

```
name: Release with commit

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.0.1
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "Version $1"
          tag_name: "v$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
```

**Comment by ChanTsune** [comment]
Hi @Thiritin 

It looks to me that the commit message doesn't match the regex that on workflow settings.

if you want to create release with alpha suffix, change regex like `"Release v((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)"`


```yaml
name: Release with commit

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.0.1
        with:
          regexp: "Release v((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)" # Changed
          regexp_options: "us"
          release_name: "Version $1"
          tag_name: "v$1"
          body: "$5" # Changed
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
```
